[package]
name = "blt"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.8", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
num_cpus = "1.16"

[dev-dependencies]
tempfile = "3.3"
